server:
  servlet:
    context-path: /functionviewer2
    session:
      cookie:
        name: 333
  port: 18080

spring:
  aop:
    proxy-target-class: true
  redis:
    host: localhost
    port: 6379
    password: password_of_redis_password_of_redis
    database: 0
    jedis:
      pool:
        max-active: 4
        max-wait: 1000ms
        max-idle: 4
